### ISSUE TITLE
Crash with Mowzie's Mobs

### ISSUE THREAD

**Issue by Catomax262** [DeeakronL/MinecraftJourneyMode#1]
https://crashy.net/Y73v1QDRXbm2yRvZHa03

**Comment by Catomax262** [comment]
P.D: It also happens with traveler's backpack, and many more. Please fix this.

**Comment by DeeakronL** [comment]
Looking into it

**Comment by DeeakronL** [comment]
Besides Mowzie's Mobs, are there any other mods that have that capability issue? I believe I've fixed it (change is currently on GitHub, but will be updated on CurseForge as soon as I fix another issue I've noticed), although I did not seem to have any issues when running Journey Mode with Traveler's Backpack.

**Comment by DeeakronL** [comment]
Issue should be resolved and both the github version and release on curseforge should have the update.
